telegram:
  bot:
    chatId: ${tg_chatId}
    name: ${tg_name}
    token: ${tg_token}
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    #url: "jdbc:sqlite:files.db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
#url: http://localhost:8080